### ISSUE TITLE
Not allowed to navigate to filesystem URL: 

### ISSUE THREAD

**Issue by MahdiAmiriDev** [JohnMarkT/scorm-player#2]
hi ! @JohnMarkT 
i have a scorm package and it fromat is zip
chose it to play scorn file
but i have this error 
how can i solve it ?
Not allowed to navigate to filesystem URL: filesystem:http://localhost:63342/persistent/TOC1/index.html

**Comment by JohnMarkT** [comment]
It appears that either the manifest file or the course files is using absolute URLs. Try switching them to relative URLs by removing any reference to "http://localhost:63342".

**Comment by MahdiAmiriDev** [comment]
i have try different ways but i can't solve it :(
 could you help me with a sample?

**Comment by JohnMarkT** [comment]
It appears that a change has been made to Chromium (https://chromestatus.com/feature/5816343679991808). I'll need some time to find a way to refactor the access of the fileSystem.

**Comment by MahdiAmiriDev** [comment]
thanks !

**Comment by JohnMarkT** [comment]
I am archiving this repo. The approach I took to access the resources within a SCORM package is no longer possible with the recent changes to Chrome. Feel free to fork this repo to attempt a work-around or different approach.
