### ISSUE TITLE
The demonstration website cannot view the uploaded zip file

### ISSUE THREAD

**Issue by pengfan8080** [JohnMarkT/scorm-player#3]
Hello, I tried to upload a scorm zip file on the demo website, but after the upload was successful, the website kept me waiting. May I know what caused this issue?

**Comment by pengfan8080** [comment]
I copied the code to my computer and opened the index page to upload, but it couldn't be played.

**Comment by JohnMarkT** [comment]
I am archiving this repo. The approach I took to access the resources within a SCORM package is no longer possible with the recent changes to Chrome. Feel free to fork this repo to attempt a work-around or different approach.
